const { chromium } = require('playwright-core')
const assert = require('node:assert/strict')
const path = require('node:path')
const fs = require('node:fs')
const root = path.resolve(__dirname, '../..')
;(async() => {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/usr/bin/chromium', headless: true, args: ['--no-sandbox'] })
  const page = await browser.newPage({ viewport: { width: 1100, height: 800 } })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(`file://${root}/.validation/catalog-queue-ui/index.html`)
  await page.locator('#open-catalog').click()
  await page.locator('.list-item').first().click({ button: 'right' })
  const menu = page.getByRole('menu', { includeHidden: true })
  await menu.waitFor({ state: 'visible' })
  const bounds = await menu.boundingBox()
  assert.ok(bounds && bounds.x >= 0 && bounds.y >= 0 && bounds.x + bounds.width <= 1100 && bounds.y + bounds.height <= 800)
  assert.equal(await menu.evaluate(el => { const r = el.getBoundingClientRect(); return el.contains(document.elementFromPoint(r.x + 15, r.y + 15)) }), true)
  await page.screenshot({ path: `${root}/.validation/catalog-queue-ui/catalog-menu.png` })
  await page.keyboard.press('Escape')
  assert.equal(await menu.getAttribute('aria-hidden'), 'true')
  await page.locator('.list-item').last().click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Play' }).press('Enter')
  assert.equal(await menu.getAttribute('aria-hidden'), 'true')
  // Close while the menu is open, then reopen: the teleported menu must not survive.
  await page.locator('.list-item').first().click({ button: 'right' })
  await page.locator('header button').click()
  await page.locator('#open-catalog').click()
  assert.equal(await page.getByRole('menu').count(), 0)
  await page.locator('header button').click()
  await page.getByRole('button', { name: 'Current playback queue', exact: true }).click()
  await page.getByRole('button', { name: 'Move up', exact: true }).nth(1).click()
  let names = await page.locator('ol > li > button').allTextContents()
  assert.deepEqual(names.map(s => s.split(' · ')[0]), ['Third song', 'Second song'])
  await page.getByRole('button', { name: 'Play next', exact: true }).nth(1).click()
  assert.deepEqual(await page.evaluate(() => window.fixture.tempPlayList.map(x => x.musicInfo.id)), ['Second song'])
  await page.getByRole('button', { name: 'Play Second song · Example artist', exact: true }).first().click()
  assert.equal(await page.evaluate(() => window.fixture.playMusicInfo.musicInfo.id), 'Second song')
  assert.equal(await page.evaluate(() => window.fixture.tempPlayList.length), 0)
  await page.screenshot({ path: `${root}/.validation/catalog-queue-ui/queue-actions.png` })
  await page.getByRole('button', { name: 'Clear queue and stop', exact: true }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  assert.equal(await page.evaluate(() => window.fixture.playMusicInfo.musicInfo.id), 'Second song')
  await page.getByRole('button', { name: 'Clear queue and stop', exact: true }).click()
  await page.getByRole('button', { name: 'Clear queue and stop', exact: true }).click()
  assert.equal(await page.evaluate(() => window.fixture.playMusicInfo.musicInfo), null)
  assert.deepEqual(await page.evaluate(() => window.fixture.saved.map(x => x.id)), ['First song', 'Second song', 'Third song'])
  assert.deepEqual(errors, [])
  const result = { passed: true, checks: ['menu topmost hit-testing', 'menu bounds', 'Escape', 'keyboard activation', 'close/reopen cleanup', 'queue reorder', 'play-next enqueue', 'specified playback', 'clear cancellation', 'clear stops state', 'saved list unchanged'], screenshots: ['catalog-menu.png', 'queue-actions.png'], scope: 'Actual Vue components and queue module in Chromium; fixture song data, audio/IPC stubbed; not packaged Electron or native OS gestures' }
  fs.writeFileSync(`${root}/.validation/catalog-queue-ui/result.json`, JSON.stringify(result, null, 2))
  console.log(JSON.stringify(result, null, 2))
  await browser.close()
})().catch(error => { console.error(error); process.exit(1) })
